feat(src/tr): New source: AnilibriaTV
aniyomiorg/aniyomi-extensions pull request #2349
Opened 2023-10-10 15:30 UTC by ToxesFoxes

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

2023-10-10 15:43 UTC, ToxesFoxes commented on src/ru/anilibriatv/src/eu/kanade/tachiyomi/animeextension/ru/anilibriatv/AniLibriaTV.kt
> +class AniLibriaTV : AnimeSourceFactory {
Fixed in next commit 👍🏻

2023-10-10 16:49 UTC, ToxesFoxes commented
I forgot to fix the main class when I transferred it to a single source, now everything works fine

2023-10-10 22:47 UTC, jmir1 requested changes

2023-10-10 22:47 UTC, jmir1 commented on src/ru/anilibriatv/res/mipmap-anydpi-v26/ic_launcher.xml
Please remove this directory and also remove all *_foreground and *_background and *_monochrome icon files.
They aren't necessary and only create issues on the website.

2023-10-10 22:47 UTC, jmir1 commented on src/ru/anilibriatv/src/eu/kanade/tachiyomi/animeextension/ru/anilibriatv/api_v3.md
Is it really necessary to include the entire API documentation?

2023-10-10 22:47 UTC, jmir1 commented on src/ru/anilibriatv/src/eu/kanade/tachiyomi/animeextension/ru/anilibriatv/AniLibriaTV.kt
> +import android.util.Log
Please remove all logging in your final extension.

2023-12-11 10:34 UTC, Secozzi commented
Closing due to inactivity, feel free to open a new pull request later with the requested changes.

2023-12-11 10:34 UTC, closed without merging