feat(multisrc/animestream/es): New source: AnimeYT.es
aniyomiorg/aniyomi-extensions pull request #2531
Opened 2023-11-20 21:55 UTC by Dark25

Checklist:

- [x] Have tested the modifications by compiling and running the extension through Android Studio

thank claudemirovsky

2023-11-21 19:12 UTC, Dark25 commented
pull ready for merger

2023-11-21 19:36 UTC, Dark25 commented
#2533 Close  change domain base  for fix error 505

2023-11-23 05:21 UTC, Claudemirovsky requested changes
Nice first contribution bro! There's just a few minor issues, but they're all easy to fix.

2023-11-23 05:21 UTC, Claudemirovsky commented on multisrc/overrides/animestream/tiodonghua/src/Tiodonghua.kt
> +    override val animeListUrl = "$baseUrl/anime"
The `AnimeStream` theme already uses this [address](https://github.com/aniyomiorg/aniyomi-extensions/blob/5a7c722b17898beb8b7241058da7067e3347e317/multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/animestream/AnimeStream.kt#L81) by default, so this line is unnecessary.

2023-11-23 05:21 UTC, Claudemirovsky commented on multisrc/overrides/animestream/tiodonghua/src/Tiodonghua.kt
> +    override fun latestUpdatesRequest(page: Int) = GET("$baseUrl/anime/?status=&type=&sub=&order=update", headers)
The [default implementation](https://github.com/aniyomiorg/aniyomi-extensions/blob/5a7c722b17898beb8b7241058da7067e3347e317/multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/animestream/AnimeStream.kt#L103) of this function is better, as it supports pagination correctly. So this override should be removed.

2023-11-23 05:21 UTC, Claudemirovsky commented on multisrc/overrides/animestream/tiodonghua/src/Tiodonghua.kt
> +    }
At least in the episodes I've tested the extension, **none** of the videos extracted had their language specified (Because none of the used video extractors are able to detect the language and add it in the video quality property), so those language preferences are kinda pointless.

2023-11-24 06:11 UTC, Claudemirovsky commented on multisrc/overrides/animestream/animeytes/src/AnimeYTES.kt
> +    override fun latestUpdatesRequest(page: Int) = GET("$baseUrl/anime", headers)
Same case as in https://github.com/aniyomiorg/aniyomi-extensions/pull/2531#discussion_r1402920252.

2023-11-24 06:11 UTC, Claudemirovsky commented on src/pt/animesvision/src/eu/kanade/tachiyomi/animeextension/pt/animesvision/AnimesVision.kt
> +    override val baseUrl = "https://tanoshi.digital"
There's an announcement in AnimesVision's discord server saying that the original domain is working correctly again (since yesterday), so this isn't needed anymore.

2023-11-24 22:11 UTC, jmir1 commented
Also please delete all the foreground, background, monochrome and xml launcher files. Only the ic_launcher.png file is needed. (See other sources)

2023-11-24 22:20 UTC, Dark25 commented
Ready 🗡️

2023-11-24 23:31 UTC, jmir1 commented on src/pt/animesvision/build.gradle
> +    extVersionCode = 22
Why are you changing this when nothing in AnimesVision is changed?

2023-11-24 23:34 UTC, jmir1 approved these changes

2023-11-25 04:24 UTC, Claudemirovsky approved these changes
10/10 LGTM

2023-11-25 09:39 UTC, merged

2024-04-08 00:52 UTC, Leviasem commented
Please add the site and turn it into an extension
https://i-egybest.info/

2024-04-08 00:54 UTC, Leviasem commented
https://i-egybest.info/[](url)