New source: Torrentio (Debird Only)
aniyomiorg/aniyomi-extensions pull request #2829
Opened 2024-01-26 18:11 UTC by ni3x

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [ ] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `containsNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [ ] Have tested the modifications by compiling and running the extension through Android Studio

This extension seamlessly integrates AniList for comprehensive metadata and utilizes the Torrentio API to gather all torrent links for Anime content.

Supported Debrid Services:
  - RealDebrid
  - Premiumize
  - AllDebrid
  - DebridLink
  - Offcloud

Users can effortlessly select their preferred Debrid service in the extension settings and input the corresponding token provided by the chosen Debrid site. Additionally, users have the flexibility to fine-tune Debrid settings based on their preferences, thanks to the customizable options available in the extension settings.

For non-Debrid users, attempting to click on an episode will trigger a toast message indicating that services are not supported or use Debird account.

Looking ahead, this extension has the potential to evolve into a powerful tool for streaming torrents if torrent support is incorporated into Aniyomi in the future.

2024-01-26 21:03 UTC, Secozzi commented
You should use the [Icon generator](https://as280093.github.io/AndroidAssetStudio/icons-launcher.html) to create square icons

2024-01-26 23:37 UTC, Claudemirovsky requested changes

2024-01-26 23:37 UTC, Claudemirovsky commented on src/all/torrentio/src/eu/kanade/tachiyomi/animeextension/all/torrentio/Torrentio.kt
> +    private val json: Json by injectLazy()
This isn't being used anywhere (.... but it really should, see the next comments)

2024-01-26 23:37 UTC, Claudemirovsky commented on src/all/torrentio/src/eu/kanade/tachiyomi/animeextension/all/torrentio/Torrentio.kt
> +            JSONArray(mediaList)
Use [kotlinx.serialization](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/basic-serialization.md) instead of `JSONObject` or `JSONArray`. You can check the code of other extensions as reference (ex: [OppaiStream](https://github.com/aniyomiorg/aniyomi-extensions/blob/83f23bdc637ddf8287cf61bbcd536d6793df8937/src/en/oppaistream/src/eu/kanade/tachiyomi/animeextension/en/oppaistream/OppaiStream.kt#L297), [Yomiroll](https://github.com/aniyomiorg/aniyomi-extensions/blob/83f23bdc637ddf8287cf61bbcd536d6793df8937/src/all/kamyroll/src/eu/kanade/tachiyomi/animeextension/all/kamyroll/Yomiroll.kt#L167)).

2024-01-26 23:37 UTC, Claudemirovsky commented on src/all/torrentio/src/eu/kanade/tachiyomi/animeextension/all/torrentio/Torrentio.kt
> +            }
This could be replaced by a [`.map{}`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/map.html) block.
```suggestion
            val tagsArray = item.getJSONArray("tags")
            val tagsList = tagsArray.indices.map { index ->
                tagsArray.getJSONObject(index).getString("name")
            }
```

Or, alternatively, if the code were using `kotlinx.serialization`:
```suggestion
            val tagsList = item.tags.map { it.name }
```

2024-01-26 23:37 UTC, Claudemirovsky commented on src/all/torrentio/src/eu/kanade/tachiyomi/animeextension/all/torrentio/Torrentio.kt
> +            anime.genre = anime.genre?.split(", ")?.sorted()?.joinToString(", ")
", " is the default separator for [`.joinString()`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/join-to-string.html), so you don't need to specify it here.
```suggestion
            // Sorting genres in ascending order
            anime.genre = combinedGenres.sorted().joinToString()
```

2024-01-26 23:37 UTC, Claudemirovsky commented on src/all/torrentio/src/eu/kanade/tachiyomi/animeextension/all/torrentio/Torrentio.kt
> +            studiosArray?.let {
Unnecessary `.let` usage, use `.also` instead.

2024-01-26 23:37 UTC, Claudemirovsky commented on src/all/torrentio/src/eu/kanade/tachiyomi/animeextension/all/torrentio/Torrentio.kt
> +        return parseSearchJson(jsonData) }
Have you compiled before submitting the changes? I mean, this project runs `ktFormat` on-build, and this certainly isn't formatted.

2024-01-26 23:37 UTC, Claudemirovsky commented on src/all/torrentio/src/eu/kanade/tachiyomi/animeextension/all/torrentio/Torrentio.kt
> +    }
You could reuse the `popularAnimeParse` function here.
```suggestion
    override fun searchAnimeParse(response: Response) = popularAnimeParse(response)
```

2024-01-26 23:37 UTC, Claudemirovsky commented on src/all/torrentio/src/eu/kanade/tachiyomi/animeextension/all/torrentio/Torrentio.kt
> +//    }
Remove this.

2024-01-26 23:37 UTC, Claudemirovsky commented on src/all/torrentio/src/eu/kanade/tachiyomi/animeextension/all/torrentio/Torrentio.kt
> +                val episodeNumber = videoObject.getInt("episode").toFloat()
```suggestion
                val episodeNumber = videoObject.getFloat("episode")
```

2024-01-26 23:37 UTC, Claudemirovsky commented on src/all/torrentio/src/eu/kanade/tachiyomi/animeextension/all/torrentio/Torrentio.kt
> +                episode.url = videoObject.getString("id").toString()
```suggestion
                episode.url = videoObject.getString("id")
```

2024-01-26 23:37 UTC, Claudemirovsky commented on src/all/torrentio/src/eu/kanade/tachiyomi/animeextension/all/torrentio/Torrentio.kt
> +        val inputFormat = SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'", Locale.getDefault())
As said in [CONTRIBUTING.md#episode](https://github.com/aniyomiorg/aniyomi-extensions/blob/master/CONTRIBUTING.md#episode):
`Make sure you make the SimpleDateFormat a class constant or variable so it doesn't get recreated for every episode.`

There's a example of how this could be done in the same section.

2024-01-27 03:55 UTC, ni3x commented
I'll fix it, might take a week. Don't close the PR.

2024-01-27 07:06 UTC, closed without merging