Updated AnyMovie url
aniyomiorg/aniyomi-extensions pull request #3223
Opened 2024-05-08 07:21 UTC by kaoru2

Fixes #2565 
Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [x] Have removed `web_hi_res_512.png` when adding a new extension

2024-05-08 07:23 UTC, Secozzi commented
Don't change the package name if you're just updating the url

2024-05-08 07:24 UTC, Secozzi commented on src/en/anymovie/src/eu/kanade/tachiyomi/animeextension/en/anymovie/AnyMovie.kt
> +    override val baseUrl = "https://anymovie.cc/"
```suggestion
    override val baseUrl = "https://anymovie.cc"
```
Remove trailing slash

2024-05-08 07:25 UTC, Secozzi commented on src/en/anymovie/src/eu/kanade/tachiyomi/animeextension/en/anymovie/AnyMovie.kt
> +    override val name = "AnyMovie"
You should keep the old `id` if you're changing the name

2024-05-08 07:50 UTC, kaoru2 commented
> Don't change the package name if you're just updating the url

The name changed from AllMoviesForYou to AnyMovie and I did something like in AniWave, should I not?

2024-05-08 07:52 UTC, Secozzi commented
> > Don't change the package name if you're just updating the url
> 
> The name changed from AllMoviesForYou to AnyMovie and I did something like in AniWave, should I not?

You shouldn't change the package name, as you can see on aniwave, the package name uses "nineanime" not "aniwave"

2024-05-12 08:37 UTC, jmir1 commented
You need to override the extension id.

Read this: https://github.com/aniyomiorg/aniyomi-extensions/blob/master/CONTRIBUTING.md#renaming-existing-sources

2024-05-12 08:38 UTC, jmir1 requested changes

2024-05-12 08:38 UTC, jmir1 commented on src/en/allmovies/src/eu/kanade/tachiyomi/animeextension/en/allmovies/AnyMovie.kt
You need to override `id`

2024-05-12 09:21 UTC, fakebhai commented
you mentioned it `fixes #2565` , so is it still WIP? because last time I checked changing baseurl doesn't fix it

2024-06-13 22:50 UTC, closed without merging